int potencia = 1;               // valor inicial da potência
int minutos = 0;                // valor inicial dos minutos
int segundos = 0;               // valor inicial dos segundos
int segundos_totais = 0;        // valor total de segundos a serem contados pelo temporizador
bool tempo_rodando = false;     // flag para saber se o temporizador está rodando
int monitor = 0;                // define em qual tela o usuário está
int cursor = 0;                 // cursor para o usuário mudar os valores
int tempoPisca = 0;
bool ledLigado = true;
unsigned long temporizador = 0;
